# do the check here...
ifdef DB
    $(error do not set the DB early, you should set XML_DB!)
endif

# now we assign the value
DB=$(O)to.yaml

#info::
#	@echo "$(DB) $(XML_DB) $(O)"

# then we create a target to get the new file. here a simple dummy-step. more complicated stuff is easily possible.
$(O)to.yaml: $(XML_DB) | $(O)
	cp $< $@

# well-behaved as we are...
clean_template::
	rm -f $(O)to.yaml
